### ISSUE TITLE
stiffness? cloth simulation?

### ISSUE THREAD

**Issue by forresto** [jpweeks/particulate-js#1]
I see angle and distance constraints can be set up with ranges. Do those correspond to springiness/stiffness? So if I want distance of 1 with play of 0.1, I'd use `[0.9, 1.1]`?

**Comment by jpweeks** [comment]
I have used small ranges to make certain relationships more relaxed, but it's not technically stiffness; all constraints have infinite stiffness and resolve to a resting position when applied. Defining a range expands the domain of state that can be considered valid and resolved. So, in the case of `DistanceConstraint` with distance `[0.9, 1.1]`: if distance is `< 0.9` the resting distance is considered to be `0.9`; if distance is `> 1.1` resting distance will be `1.1`; any distance in-between will be a no-op.

**Comment by forresto** [comment]
Thinking about the 3d form of a pair of jeans, distance of any vertex of the mesh could be ~0 (folded or crumpled). The maximum would be hard (denim doesn't stretch much).

So could I apply forces (or angle constraints) to the mesh to inflate the form?

**Comment by forresto** [comment]
(For reference, I'm building a vector editor for cloth patterns, and I'm experimenting with Particulate for visualizing the sewn form.)

**Comment by jpweeks** [comment]
Hm, I'm not sure I understand your question.

**Comment by forresto** [comment]
Could Particulate simulate a cloth-like mesh, that "inflates" itself? How does that translate to constraints and forces?

**Comment by jpweeks** [comment]
It should be possible, but the arrangement of constraints will depend on the shape of the mesh and along what dimensions you want it to inflate. You will likely need constraints defining the outer perimeter as well as inner volume; i.e. [volumetric cloth cross-section](https://docs.google.com/drawings/d/1rEcRHbYB9QVxzlVKYZ5hC0q1uYm2JcZGghuWPXs0i7I/).
Distance of a `DistanceConstrant` can be updated with [`setDistance`](https://github.com/jpweeks/particulate-js/blob/master/src/constraints/DistanceConstraint.js#L62).

**Comment by forresto** [comment]
This is the demo that I had in mind with meshes that "inflate" and have some gravity to the middle of the screen: http://bl.ocks.org/christophermanning/1703449
