### ISSUE TITLE
Attract / Repulse

### ISSUE THREAD

**Issue by kohaistyle** [jpweeks/particulate-js#2]
Hi ! 
First, very nice work on the lib ... easy and sleek !

Just a question, glancing through the code i saw a ATTRACTOR_REPULSOR type for forces, but didn't see it implemented in the force code. Is it a planned feature ?

I'll to use the code with Babylon.js, by the way :)

**Comment by jpweeks** [comment]
Thanks! I'm glad you're liking it 😄 

The included forces are really basic and I agree their current options aren't the most intuitive; those constants are currently only used in [`PointForce`](https://github.com/jpweeks/particulate-js/blob/0.3.3/src/forces/PointForce.js). You will probably want to write your own force classes; this is what I've been doing for my own projects.
